// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingApi.Data;

#nullable disable

namespace WeddingApi.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20260301043333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("WeddingApi.Classes.WeddingGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeddingGuests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAttending = false,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            IsAttending = false,
                            Name = "Jane Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
