// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeddingApi.Data;

#nullable disable

namespace WeddingApi.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20260302014927_SyncGiftModels")]
    partial class SyncGiftModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeddingApi.Classes.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("WeddingApi.Classes.GiftPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GiftId")
                        .HasColumnType("integer");

                    b.Property<bool>("PaymentConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaymentConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PixCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchasedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaserEmail")
                        .HasColumnType("text");

                    b.Property<string>("PurchaserPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GiftId");

                    b.ToTable("GiftPurchases");
                });

            modelBuilder.Entity("WeddingApi.Classes.WeddingGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeddingGuests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAttending = false,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            IsAttending = false,
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("WeddingApi.Classes.GiftPurchase", b =>
                {
                    b.HasOne("WeddingApi.Classes.Gift", "Gift")
                        .WithMany("Purchases")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("WeddingApi.Classes.Gift", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
